Some work I did on ant starless a while ago before I got massively derailed trying to solve everything about bash.

diff --git a/ant-starless b/ant-starless
--- a/ant-starless
+++ b/ant-starless
@@ -1,43 +1,61 @@
-#!/bin/bash
+#!/usr/bin/env bash
+#
 # Runs the ant build while first resolving artifacts.
+# At the moment: ./ant-starless test-1
+#
 
-base_directory="$(dirname $0)"
-starr_version_file="$(dirname $0)/lib/starr.version"
-desired_starr_version_file="$(dirname $0)/starr.version"
+. $(dirname $0)/tools/bash-fns.sh
 
-# Check the current stored launch version.
-if [[ -f "$starr_version_file" ]]; then
-  current_starr_version="$(cat $starr_version_file)"
-else
-  current_starr_version=""
-fi
+[[ $# -gt 0 ]] || { echo "Usage: $0 <starr version>" ; exit 1; }
 
-# Load desired STARR version.
-if [[ -f "$desired_starr_version_file" ]]; then
-  desired_starr_version="$(cat $desired_starr_version_file)"
-else
-  echo "Could not find a STARR version file ($desired_starr_version_file).  Please specify one"
-  exit 1
-fi
+# declare -r base_directory=$(cd $(dirname $0) ; pwd)
+declare -r starr_dir="$script_directory/lib"
+declare -r libraryJar="$starr_dir/scala-library.jar"
+
+# reads the version from the jar properties file
+libraryJarVersion () {  
+  local line=$(
+    cd $(mktemp -dt starrless) && 
+    jar xf "$libraryJar" library.properties &&
+    grep ^version.number= library.properties &&
+    rm -f library.properties
+  )
+  echo ${line#version.number=}
+}
+
+declare -r desiredStarr="$1"
+declare -r currentStarr=$(libraryJarVersion)
 
 # This will load a scala-starr jar into the desired location.
 # Arg 1: Artifact name
 # Arg 2: Artifact version
 # Note: organization and repository are all assumed to be the same.
 function loadStarrJar() {
-  url="http://typesafe.artifactoryonline.com/typesafe/starr-releases/org/scala-lang/bootstrap/$1/$2/$1-$2.jar"
-  loc="$base_directory/lib/$1.jar"
-  if [[ $(which curl) ]]; then
-    echo "downloading [$1]..."
-    curl --silent "$url" > "$loc"
-    return $?
+  local name="$1"
+  local jarname="$name-$desiredStarr.jar"
+  local urlbase="http://typesafe.artifactoryonline.com/typesafe/starr-releases/org/scala-lang/bootstrap"
+  local url="$urlbase/$name/$desiredStarr/$jarname"
+
+  # todo: we should be going through the ivy cache.
+  # the only thing to download with curl is something to get dependencies
+  # correctly (could be sbt, or ivy directly, or something lighter weight)
+  if which curl >/dev/null; then
+    echo "downloading $jarname..."
+    set +e
+    http_code=$(curl --write-out '%{http_code}' --silent --fail --output "$starr_dir/$jarname" "$url")
+    if (( $? != 0 )); then
+      echo "Error downloading $name: response code $http_code"
+      echo "$url"
+      exit 1
+    fi
+    set -e
   else
     cat <<EOM
-No means of downloading $1.jar found.   Either:
+No means of downloading $name.jar found.   Either:
  * install curl
  * install wget
  * manually download: $url
-        and place at: $loc
+        and place at: $outjar
 EOM
     return 0
   fi
@@ -45,20 +63,14 @@ EOM
 
 # This will load a version of star and update the starr_version_file with the new version.
 function loadStarr() {
-  loadStarrJar "scala-library" $1
-  loadStarrJar "scala-compiler" $1
-  loadStarrJar "forkjoin" $1
-  loadStarrJar "fjbg" $1
-  loadStarrJar "msil" $1
-  loadStarrJar "jline" $1
-  echo $1 >$starr_version_file
+  for jar in scala-library scala-compiler forkjoin fjbg msil jline; do
+    loadStarrJar $jar
+  done
 }
 
 # Check to see if we should load starr.
-if [[ "$current_starr_version" != "$desired_starr_version" ]]; then
-  loadStarr $desired_starr_version
-fi
+[[ "$currentStarr" == "$desiredStarr" ]] || loadStarr
 
 # Now, delegate to ANT.
 # TODO - make sure ANT_OPTS are exported or whatever needs to happen here...
-ant $@
+ant "$@"
